python run_summarization.py \
    --model_name_or_path /home/ypd-19-2/docomo/checkpoints_decode_eval_1.0 \
    --do_predict \
    --train_file /home/ypd-19-2/docomo/jsonl/train.json \
    --validation_file /home/ypd-19-2/docomo/jsonl/val.json \
    --test_file /home/ypd-19-2/docomo/data_source_target/train/test.json \
    --source_prefix "summarize: " \
    --output_dir /home/ypd-19-2/docomo/checkpoints_decode_eval_1.0 \
    --overwrite_output_dir  \
    --gradient_accumulation_steps=4 \
    --per_device_train_batch_size=16 \
    --per_device_eval_batch_size=8 \
    --save_total_limit=1 \
    --eval_steps=50 \
    --save_steps=15000 \
    --logging_steps=50 \
    --num_train_epochs=4.0 \
    --learning_rate=1e-3 \
    --predict_with_generate \
    --pre_seq_len=200